[package]
name = "manifolds-visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.1.1", features = ["constructor"] }
font8x8 = "0.3.1"
itertools = "0.14.0"
minifb = "0.28.0"
nalgebra = "0.34.1"
